apiVersion: v1
kind: pod
metadata:
  name: worker-app-pod
  labels:
    name: worker-app-pod
    app: demo-voting-app
spec:
  containers:
  - image: dockersamples/examplevotingapp_worker
    name:  worker-app